name: gust_cron 

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.13"

jobs:
  gust:
    runs-on: ubuntu-latest

    env:
      GUST_SENDER: ${{ secrets.GUST_SENDER }}
      GUST_SENDER_PASSWORD: ${{ secrets.GUST_SENDER_PASSWORD }}
      GUST_RECIPIENT: ${{ secrets.GUST_RECIPIENT }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python and install dependencies
        uses: ./.github/actions/setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          dependencies: dev

      - name: Generate and send daily gust
        run: gust --model gemini-2.5-flash
